### ISSUE TITLE
Stuck in trouble of getting ICC models.

### ISSUE THREAD

**Issue by kordood** [JordanSamhi/RAICC#3]
Hi! I'm trying to get ICC models.

I stuck a problem with starting to use this tool.

(A)
For a stable environment, I intended to download the VM you posted.
But, I can't access the VM.
The page in [VM_LOCATION ](https://dropit.uni.lu/invitations?share=75ca6f9f1f253da9170d&dl=0)represents **"This public link is no longer valid."**

(B)
I successfully built this tool until step 6 on my docker(in ubuntu:18.04).
After then, I met the **NullpointException** while running **_process_droidbench_apps_with_raicc.sh_**.
I also ran launch_raicc.sh like the following, there was no difference.

It uncertainly seems to cause by [class_path](https://github.com/soot-oss/soot/issues/1249).

I want to reproduce your experimental result for gaining ICC models.
I hope to **use the VM** if it is available.

```
root@7043169a0e16:/home/raicc/git/RAICC/artefacts/tools# ./launch_raicc.sh /home/raicc/git/RAICC/artefacts/droidbench/apks/sendTextMessage1.apk
Exception in thread "main" java.lang.NullPointerException
        at soot.JastAddJ.Program.initPaths(Program.java:350)
        at soot.SootResolver.<init>(SootResolver.java:87)
        at soot.Singletons.soot_SootResolver(Singletons.java:802)
        at soot.SootResolver.v(SootResolver.java:91)
        at soot.Scene.tryLoadClass(Scene.java:670)
        at soot.Scene.loadBasicClasses(Scene.java:1268)
        at soot.Scene.loadNecessaryClasses(Scene.java:1347)
        at lu.uni.preprocessIntentSender.ISPreprocessor.initializeSoot(ISPreprocessor.java:112)
        at lu.uni.preprocessIntentSender.ISPreprocessor.run(ISPreprocessor.java:43)
        at lu.uni.trux.raicc.Main.main(Main.java:45)
```

**Comment by JordanSamhi** [comment]
Hello @kordood,

The VM is no longer available since it was intended for the ICSE artifact evaluation track.

However, based on your comment it seems that you successfully configured the environment, it should then be ok to run RAICC.

I was able to reproduce your error, you are most likely not using Java 8. Please consider using **Java 8** and try again, it should do the trick.

**Comment by kordood** [comment]
Thank you, @JordanSamhi!

I used OpenJDK version 1.8.0_292.
But RAICC works well with oracle JDK 1.8.0_301 as following your recommendation.

Could I ask one more question? (Not important)
What is the role of the CSV file in results?
It makes curious for me because the file is always empty whenever I get results.

**Comment by JordanSamhi** [comment]
I am glad that it works.

The csv file has absolutely no interest here, it is just an output file generated by IC3, which RAICC relies on.
You can even see that in `process_droidbench_apps_with_raicc.sh`, csv files are removed.

**Comment by kordood** [comment]
Thanks for telling me :)

I made a Dockerfile while using RAICC, it may be useful to build the initial environment.
